macos ready

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -13,6 +13,11 @@ cleanup() {
   echo "$(caller): ${BASH_COMMAND}"
 }
 
+fail() {
+  printf '%s\n' "$1" >&2
+  exit "${2-1}"
+}
+
 semver_ge() {
   printf '%s\n%s\n' "$2" "$1" | sort --check=quiet --version-sort
 }
@@ -23,12 +28,14 @@ install_poetry() {
   local install_path=$3
   local flags=
 
+  export POETRY_CONFIG_FILE="$HOME/Library/Application Support/pypoetry/config.toml"
+  export POETRY_CONFIG_DIR="$HOME/Library/Application Support/pypoetry/$version"
+  export POETRY_HOME="$install_path"
+
   if [ "$install_type" == "version" ]; then
-    semver_ge "$MISE_INSTALL_VERSION" 1.1.7 && install_vercomp="ge" || install_vercomp="lt"
-    semver_ge "$MISE_INSTALL_VERSION" 1.2.0 && config_vercomp="ge" || config_vercomp="lt"
+    semver_ge "$MISE_INSTALL_VERSION" 1.7.0 && install_vercomp="ge" || install_vercomp="lt"
   else
     install_vercomp="ge"
-    config_vercomp="lt"
   fi
 
   if [[ -n ${MISE_POETRY_INSTALL_URL:-} ]]; then
@@ -36,31 +43,30 @@ install_poetry() {
   elif [ "$install_vercomp" == "ge" ]; then
     install_url="https://install.python-poetry.org"
   else
-    install_url="https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py"
-  fi
-
-  if [[ $install_url == *get-poetry* ]]; then
-    flags=--no-modify-path
+    fail "Error: Please avoid using ancient Poetry versions prior to 1.7.0"
   fi
 
   if [ "$install_type" = "version" ]; then
-    curl -sSL "$install_url" | POETRY_HOME=$install_path python3 - --version "$version" $flags
+    curl -sSL "$install_url" | sed 's/symlinks=False/symlinks=True/' | python3 - --version "$version" $flags
   elif [ "$install_type" = "ref" ]; then
-    curl -sSL "$install_url" | POETRY_HOME=$install_path python3 - --git https://github.com/python-poetry/poetry.git@"$version" $flags
+    curl -sSL "$install_url" | sed 's/symlinks=False/symlinks=True/' | python3 - --git https://github.com/python-poetry/poetry.git@"$version" $flags
   else
-    fail "unknown install type"
+    fail "Error: Unknown install type"
   fi
 
-  if [ "$config_vercomp" == "ge" ]; then
-    # Ensure that poetry behaves as expected with mise python (pyenv)
-    echo Configuring poetry to behave properly with mise ...
-    echo Running: \"poetry config virtualenvs.prefer-active-python true\".
-    echo ""
-    "$install_path"/bin/poetry config virtualenvs.prefer-active-python true
-  else
-    echo Warning: Poetry versions prior to 1.2.0 may not work properly with mise.
-    echo Consider upgrading to a later version.
-    echo https://github.com/asdf-community/asdf-poetry/issues/10
+  # Ensure that Poetry behaves as expected with mise python (pyenv)
+  "$install_path"/bin/poetry config virtualenvs.prefer-active-python true
+  echo Adding the ML Platform configuration...
+  if [ ! -f "$POETRY_CONFIG_FILE" ]; then
+    "$install_path"/bin/poetry config virtualenvs.in-project true
+
+    /bin/cp -rf "$POETRY_CONFIG_DIR/config.toml" "$POETRY_CONFIG_FILE"
+  fi
+  ln -Fs "$POETRY_CONFIG_FILE" "$POETRY_CONFIG_DIR/config.toml"
+
+  if [ -n "$MISE_TOOL_OPTS__PLUGINS" ]; then
+    "$install_path"/bin/poetry self add "poetry-dotenv-plugin@${MISE_TOOL_OPTS__DOTENV:-latest}"
+    "$install_path"/bin/poetry self add "keyrings.google-artifactregistry-auth@${MISE_TOOL_OPTS__KEYRING:-latest}"
   fi
 }
 
